[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
# Controversial, but HTML email is on by default (highly sanitized).
# Note that HTML emails massively expand the dependency tree
default = ["html"]
html = ["ammonia"]

[dependencies]
mailparse = "0.13"
url = "2"
hex = "0.4"
sha3 = "0.10"
mbox-reader = "0.2.0" #unamaintained, should remove dep
pico-args = "0.4.1"
askama = "0.10"
anyhow = "1.0"
quick-xml = "0.22"
ammonia = {version = "3", optional = true}
