[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
default = []

[dependencies]
anyhow = "1.0.52"
nanotemplate = "*"
mail-parser = "*" # TODO no-default

# Small, effective dependencies, little benefit to vendoring
linkify = "0.8.0" 
urlencoding = "2.1.0"
nanohtml2text = "0.1.2" # TODO rem

# Should be in stdlib
once_cell = "1.9.0"
