[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
default = []

[dependencies]
anyhow = "1.0.52"
nanotemplate = "*"
# using my fork just to upstream patches faster
mail-parser = {git = "https://github.com/alexwennerberg/mail-parser", default-features=false}
# TODO cleanup dependencies
mail-builder = "*"

# Small, effective dependencies, little benefit to vendoring
linkify = "0.8.0" 
urlencoding = "2.1.0"

# Should be in stdlib
once_cell = "1.9.0"
