[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
default = []

[dependencies]
anyhow = "1.0"
horrorshow = "0.8"
linkify = "0.8" 
mailparse = "0.13"
maildir = "0.5.0"
once_cell = "1.9"
urlencoding = "2.1"
nanohtml2text = "0.1.1"
