[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
# Controversial, but HTML email is on by default (highly sanitized).
# Note that HTML emails massively expand the dependency tree
default = []
html = ["ammonia"]

[dependencies]
ammonia = {version = "3", optional = true}
anyhow = "1.0"
askama = {version = "0.10", default_feature = false}
hex = "0.4"
linkify = "0.8.0" 
mailparse = "0.13"
mbox-reader = "0.2.0" #unamaintained, should remove dep
once_cell = "1.9"
pico-args = "0.4.1"
quick-xml = "0.22"
sha3 = "0.10"
urlencoding = "2.1.0"
