[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
default = []

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
horrorshow = "0.8"
linkify = "0.8" 
mailparse = "0.13"
maildir = "0.5.0"
once_cell = "1.9"
sha3 = "0.10"
urlencoding = "2.1"
