[package]
name = "crabmail"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[features]
default = []

[dependencies]
anyhow = "1.0"
horrorshow = "0.8.4"
linkify = "0.8.0" 
mailparse = "0.13"
once_cell = "1.9"
pico-args = "0.4.1"
quick-xml = "0.22"
sha3 = "0.10"
urlencoding = "2.1.0"
